# Generated by Django 5.0.3 on 2024-09-04 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR_scan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdata',
            name='prodcut_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='productdata',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        )
    ]
