# Generated by Django 5.0.3 on 2024-09-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('prodcut_id', models.AutoField(primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
                ('weight_unit', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('value_unit', models.CharField(max_length=50)),
                ('qr_data', models.CharField(max_length=100)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
