# Generated by Django 5.0.3 on 2024-09-04 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws_camera', '0002_productdata_id_alter_productdata_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='productdata',
            name='prodcut_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
