# Generated by Django 5.0.3 on 2024-11-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws_camera', '0007_product_receipt_delete_productdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='product_id',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
