# Generated by Django 5.0.3 on 2024-11-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws_camera', '0008_rename_product_id_receipt_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='recept_id',
            new_name='receipt_id',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='product_name',
        ),
        migrations.AddField(
            model_name='receipt',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='product',
        ),
        migrations.AddField(
            model_name='receipt',
            name='product',
            field=models.ManyToManyField(to='ws_camera.product'),
        ),
    ]
